version: '3.1'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 9000:9000
    environment:
    - REDIS_DNS=redis

    

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - backend
    environment:
      - BACKEND_DNS=backend

  redis:
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
