apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jolun18/fortune-cookie-backend:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_DNS
          value: "redis"