apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: pvc-redis
    app: efk
  name: pvc-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi