apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: redis
  name: redis
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi